### ISSUE TITLE
Typescript declaration file

### ISSUE THREAD

**Issue by g-otn** [edyspider/validate-nif#26]
Hello, I'd like to use this library on my Typescript project, but the bundle published to npm doesn't have any Typescript source code or declaration files (`.d.ts`)

I'd be nice if they were included / generated with the bundle so this library could be used within Typescript project without errors.

I'm using typescript 5.3.3

```
Could not find a declaration file for module '@edyspider/validate-nif'. 'node_modules/@edyspider/validate-nif/dist/bundle.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/edyspider__validate-nif` if it exists or add a new declaration (.d.ts) file containing `declare module '@edyspider/validate-nif';`ts(7016)
```

**Comment by g-otn** [comment]
For now I've manually added this declaration into my project files:
```ts
// edyspider__validate-nif.d.ts
declare module '@edyspider/validate-nif' {
  export function validateNIF(nif: string): boolean;
}
```

**Comment by edyspider** [comment]
Hello!
Thank you for your reply.

With this new version, you can use this library in typescript projects.

If you still have some issues, please let me know.

Thank you

**Comment by g-otn** [comment]
Hello @edyspider, thanks!

But it seems the new versions published to npm do not include the new `.d.ts` file, I believe because of this project webpack settings.

https://www.npmjs.com/package/@edyspider/validate-nif/v/1.7.8?activeTab=code
